### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mtc2013** [gratifychat/botkit-mock#10]
In this repo, you have no license listed, but on npm you have MIT.  

https://www.npmjs.com/package/botkit-mock

Can you sort out a license for this repo, please?

**Comment by amplicity** [comment]
Thanks for reporting. Will sort this out and close.

**Comment by ihorrusi** [comment]
@mtc2013 sorry for the delay

**Comment by amplicity** [comment]
Was improperly closed. Probably MIT. We'll close this when we push up a license and update the readme.

**Comment by amplicity** [comment]
Added here: https://github.com/gratifychat/botkit-mock/commit/f64d687691fefd4954d5104391ce63ac9aa12bf4
