### ISSUE TITLE
replyWithTyping is not supported

### ISSUE THREAD

**Issue by giorgosera** [gratifychat/botkit-mock#19]
Hey everyone. Excellent work on this mock module. 

I just try to use it and it seems that atm if I use [ `replyWithTyping`](https://github.com/howdyai/botkit/blob/master/readme-facebook.md#simulate-typing) it doesn't work. 

Looking at the source code is not supported. Should I create a new PR or is it something you are currently working on?

**Comment by ihorrusi** [comment]
see commit `b84c9448a4d18906afaad963269de2f6c6e090d4`

**Comment by giorgosera** [comment]
Excellent work @ihorrusi ! Thanks for the quick fix :)
