### ISSUE TITLE
How to write test case for the conversations? also its failing as convo.on function is not available in botMock.js

### ISSUE THREAD

**Issue by aravindtal** [gratifychat/botkit-mock#26]
How to test conversations, I have a controller which asks the ques to user on "Who am I", if user haven't already given his name asks the user his name, Then if user provides the name then it confirms with user and then it ends the conversation. Is it possible to test conversations, any leads would be really helpful.

**Pseudo Code**
```
controller.hears("who am i", function(bot, message)) {
     bot.startConversation(message, function(err, convo) {
           convo.ask('What should I call you?', function(response, convo) {
                convo.ask('You want me to call you `' + response.text + '`?', [
                    {
                        pattern: 'yes',
                        callback: function(response, convo) {
                            convo.next();
                        }
                    },
                    {
                        pattern: 'no',
                        callback: function(response, convo) {
                            convo.stop();
                        }
                    },
                    {
                        default: true,
                        callback: function(response, convo) {
                            convo.repeat();
                            convo.next();
                        }
                    }
                ]);
                convo.next();
            }, {'key': 'nickname'}); // store the results in a field called nickname
            convo.on('end', function(convo) {
                 //Some odd logic here
            }
     });
} 
```

**Comment by amplicity** [comment]
Hey yes, totally possible to test that conversation thread. Did you check the readme?

As for convo.on, we currently do not support that so the error you are receiving is expected. We will add convo.on functionality and close this issue as soon as we push. As of current, you won't be able to test the convo.on functionality in that thread.

**Comment by aravindtal** [comment]
@amplicity I did check the readme, I couldn't find anything useful.
Actually I am using this for writing testcases of FB messenger bot, I had to go through the code to make it work for the normal test cases as it was not working until I pass the **type: message_received** in userInput, but still I am stuck for conversation.

It would be really helpful if you can give a sample test code for the above pseduo code in case of conversation.

**Comment by amplicity** [comment]
I know we are unable to test the `key` part of your code, because we do not have local storage implemented (yet).

With that said, does something like this work?
```

it('should return expected message', (done) => {
    var self = this;
    return self.controller.usersInput(
        [
            {
                first: true,
                messages: [
                    {
                        text: 'who am i', isAssertion: true
                    },
                    {
                        text: 'james', isAssertion: true
                    }
                ]
            }
        ]
    ).then((text) => {
        assert.equal(text, 'You want me to call you james?');
        done()
    })
});
```

**Comment by aravindtal** [comment]
Hi @amplicity, thank u and sorry for delay in reply
I have tried with the above code it worked. I have fee questions I will post them after more exploration.

**Comment by aravindtal** [comment]
Closed it accidentally

**Comment by amplicity** [comment]
We will close this for now. Please open up another issue with any other problems you have. We're working to add support for the additional functions you're using in your code. We will update this issue (https://github.com/gratifychat/botkit-mock/issues/14) when we're complete!

**Comment by aravindtal** [comment]
@amplicity 
```
on() {
 }
```
Dummy function should be present in botMock.js or else it breaks with the error
..TypeError: convo.on is not a function
    at /MyDir/Automation/botkitmock_sample/controller.js:135:31
    at Bot.startConversation (/MyDir/Automation/botkitmock_sample/node_modules/botkit-mock/botkit-mock/botMock.js:159:9)
    at /MyDir/Automation/botkitmock_sample/controller.js:103:21
    at Object.get (/MyDir/Automation/botkitmock_sample/node_modules/botkit-mock/botkit-mock/botMock.js:58:21)
    at Object.callback (/MyDir/Automation/botkitmock_sample/controller.js:99:34)
    at Controller.initialUserMessage (/MyDir/Automation/botkitmock_sample/node_modules/botkit-mock/botkit-mock/botMock.js:262:20)
    at Promise (/MyDir/Automation/botkitmock_sample/node_modules/botkit-mock/botkit-mock/botMock.js:230:18)
    at Controller.usersInput (/MyDir/Automation/botkitmock_sample/node_modules/botkit-mock/botkit-mock/botMock.js:203:16)
    at Object.it (/MyDir/Automation/botkitmock_sample/spec/botkit-mock.spec.js:65:32)
    at attemptAsync (/MyDir/Automation/botkitmock_sample/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1980:24)

**Comment by amplicity** [comment]
We don't support on() yet. Our new version will. You can add this to your
own local branch to temporarily mitigate this issue.

**Comment by amplicity** [comment]
Thanks for letting us know
